name: Validate data

on:
  pull_request:
    branches:
    - main
    types: [opened,synchronize]
    paths:
     - 'data/**'
     - '.github/workflows/data-tester.yml'
     - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Generate
      run: |
        make generator
    
